from django.db import models
class Count(models.Model):
    a_2w=models.IntegerField()
    a_3w=models.IntegerField()
    a_sc=models.IntegerField()
    a_bc=models.IntegerField()
    b_2w=models.IntegerField()
    b_3w=models.IntegerField()
    b_sc=models.IntegerField()
    b_bc=models.IntegerField()
    c_2w=models.IntegerField()
    c_3w=models.IntegerField()
    c_sc=models.IntegerField()
    c_bc=models.IntegerField()
    d_2w=models.IntegerField()
    d_3w=models.IntegerField()
    d_sc=models.IntegerField()
    d_bc=models.IntegerField()
    e_2w=models.IntegerField()
    e_3w=models.IntegerField()
    e_sc=models.IntegerField()
    e_bc=models.IntegerField()
    f_2w=models.IntegerField()
    f_3w=models.IntegerField()
    f_sc=models.IntegerField()
    f_bc=models.IntegerField()
    g_2w=models.IntegerField()
    g_3w=models.IntegerField()
    g_sc=models.IntegerField()
    g_bc=models.IntegerField()
    h_2w=models.IntegerField()
    h_3w=models.IntegerField()
    h_sc=models.IntegerField()
    h_bc=models.IntegerField()
#32 Buttons
